---
title: "Spring 2022 RSQA Worksheet"
author: "Noe Reyna"
date: "1/26/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---
#Loading data into R
```{r}
setwd("G:/My Drive/ComputationalStuff/UrbanEcosystems/Git/RSQA_worksheet")
library('tidyverse', 'readr')
library('dplyr')
mydata <- read.csv('1.21.2022.CSQA_ConstituentGroups=Organics,Pesticides/Results.csv')
# View(mydata)

# 12. show the frequency of parameter measurements done based on the PARM_NM column
exp_count <- mydata %>% 
  group_by(PARM_NM) %>% 
  summarise(count=n())

# create hist
param_count_hist <- ggplot(exp_count, aes(count)) +
  geom_histogram(binwidth=50) +
  labs(title='Distribution showing the number of a unique parameter\'s
  measurements [x] and respective frequency [y]', x='Measurements on a unique
  parameter') +
  theme_classic()
param_count_hist

# arrange exp_count to only contain >50 observations in desc order
exp_count <- exp_count[exp_count$count>50,]
exp_count <- exp_count[order(exp_count$count, decreasing=TRUE), ]
# view(exp_count)
```


#Plotting one parameter
```{r}
# pick parameter want to work w/ 
imidacloprid_data <- mydata[mydata$PARM_NM=='Imidacloprid, wf', ] # filter also could be used here

# make scatter plot RESULT_VA~PARM_NM [note: this is suppose to be wrong]
results_parm_scat <- ggplot(imidacloprid_data, aes(PARM_NM, RESULT_VA)) +
  geom_point()
results_parm_scat # use geom_jitter() since they're ontop of each other
# will be doing jitterplot instead since clustered
results_parm_jit <- ggplot(imidacloprid_data, aes(PARM_NM, RESULT_VA)) +
  geom_jitter() +
  theme_classic() +
  theme(axis.text=element_blank()) +
  labs(title='CSQA Measurement of Imidacloprid',
       x='Imidacloprid', y='Concentration Detected [ng/l]')
  
results_parm_jit
```


#Plotting multiple parameters
```{r}
# select the top five parameters from mydata
top_5_data <- mydata[mydata$PARM_NM %in% exp_count$PARM_NM[1:5], ]
top_5_jitterplot <- ggplot(top_5_data, aes(PARM_NM, RESULT_VA)) +
  geom_jitter(aes(color=PARM_NM)) +
  theme_classic() +
  theme(axis.text.x=element_blank()) +
  labs(title='CSQA Measurement of Various Chemicals',
       x='Chemical', y='Concentration Detected [ng/l]')
top_5_jitterplot

# instead, create a facet plot
top_5_facet <- ggplot(top_5_data, aes(PARM_NM, RESULT_VA)) +
  geom_jitter(aes(color=PARM_NM), alpha=0.35) +
  facet_wrap(.~PARM_NM, scales='free') +
  theme_classic() + theme(axis.text.x=element_blank(),
                          strip.text.x=element_blank(),
                          axis.title.x=element_blank()) +
  labs(col='Chemical', y='Concentration', title='CSQA Chemical Concentration in Stream Samples') +
  scale_color_hue(labels=c('AMPA [ug/l]', 'Glufosinate [ug/l]', 'Glyphosate [ug/l]', 'Imidacloprid [ng/l]', 'Myclobutanil [ng/l]'))

top_5_facet
```


#Plotting data on maps
```{r}
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(rgeos)

# from the Sites.csv, join top_5_data to have coords needed for mapping
getwd()
setwd('1.21.2022.CSQA_ConstituentGroups=Organics,Pesticides')

sites <- read.csv('Sites.csv')
# head(sites)
# head(top_5_data)

top_5_joined <- left_join(top_5_data, sites, by='SITE_NO')
# view(top_5_joined)

# create world map
world <- ne_countries(scale='medium', returnclass='sf')
world_map <- ggplot(world) +
  geom_sf() +
  theme_classic() +
  labs(title='World Map', x='Longitude', y='Latitude')
world_map

# plot data onto world map
# change title
world_map <- ggplot(world) +
  geom_sf() +
  theme_classic() +
  labs(title='Map of CSQA Top 5 Contaminants in CSQA sampling sites',
       x='Longitude', y='Latitude')
world_map

# add scatter plot
world_map <- ggplot(world) +
  geom_sf() +
  theme_classic() +
  labs(title='Map of CSQA Top 5 Contaminants in CSQA sampling sites',
       x='Longitude', y='Latitude',
       subtitle=paste0('A total of ',(length(unique(sites$SITE_NO))), 'sites')) +
  geom_point(data=top_5_joined, aes(DEC_LONG_VA, DEC_LAT_VA), size=1, shape=19) +
  coord_sf(xlim=c(min(sites$DEC_LONG_VA) - 1, max(sites$DEC_LONG_VA) + 1),
           ylim=c(min(sites$DEC_LAT_VA) - 1, max(sites$DEC_LAT_VA) + 1))
world_map
```



#Replicating plots
##Fig1
```{r}
getwd()
# Fig1
# get data; filter for Pyrene, solids
# setwd('RSQA_Problemset_Spring2022')
fig1_data <- read_csv('RSQA_Problemset_Spring2022/Results.csv')
# View(fig1_data)
fig1_data <- fig1_data %>% 
  filter(PARM_NM=='Pyrene, solids') %>% 
  group_by(SITE_NO) %>%
  top_n(1, RESULT_VA) %>% 
  select(SITE_NO, RESULT_VA, COUNTY_NM)
# make jitter plot
ggplot(fig1_data, aes(COUNTY_NM, RESULT_VA)) +
  geom_jitter(aes(col=COUNTY_NM)) +
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.text.x.bottom= element_blank()) +
  labs(y='Max Concentration of Pyrene per site (ug/kg)', col='Californian County')
```
##Fig2
```{r}
# Fig2
fig2_sites <- read.csv('RSQA_Problemset_Spring2022/Sites.csv')
fig2_data <- fig1_data
fig2_data_joined <- left_join(fig2_data, fig2_sites, by='SITE_NO')

# create world map
fig2_world <- ne_countries(scale='medium', returnclass='sf')
fig2_world_map <- ggplot(fig2_world) +
  geom_sf() +
  scale_size_continuous(range=c(1,10), breaks=c(50, 100, 150, 200))+
  # theme_bw() +
  # scale_size_continuous(breaks=(50, 1000, 150, 200)) +
  # scale_size_area(breaks=c(50, 100, 150, 200)) +
  labs(title='World Map', x='Longitude', y='Latitude') +
  geom_point(data=fig2_data_joined, aes(DEC_LONG_VA, DEC_LAT_VA, size=RESULT_VA, color=COUNTY_NM.x),shape=16, alpha=0.45) +
  labs(title='Map of California Sampling Sites',
       subtitle=paste0('A total of ', (length(fig2_data_joined$SITE_NO)), ' sites'),
       color='Californian County', size='Max Pyrene concentration (ug/kg)', 
       alpha=NA)+
  coord_sf(xlim=c(min(sites$DEC_LONG_VA)-1, max(sites$DEC_LONG_VA)+1),
           ylim=c(min(sites$DEC_LAT_VA)-1, max(sites$DEC_LAT_VA)+1))
fig2_world_map
```
##Fig3
```{r}
fig3_data <- read_csv('RSQA_Problemset_Spring2022/Results.csv')
# first check which has most counts
fig3_data %>% 
  group_by(PARM_NM) %>% 
  summarise(counts=n()) %>% 
  arrange(desc(counts)) %>%
  head() # imidaloprid, myclobutanil, ampa, glufosinate, gyphosate TOP 5

fig3_data <- fig3_data %>% 
  filter(PARM_NM=='Imidacloprid, wf') %>% 
  group_by(SITE_NO) %>%
  top_n(1, RESULT_VA) %>% 
  select(SITE_NO, RESULT_VA, COUNTY_NM)
# make jitter plot
ggplot(fig1_data, aes(COUNTY_NM, RESULT_VA)) +
  geom_jitter(aes(col=COUNTY_NM)) +
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.text.x.bottom= element_blank()) +
  labs(y='Max Concentration of Imidacloprid per site (ug/kg)', col='Californian County')
```
```{r}
fig4_sites <- read.csv('RSQA_Problemset_Spring2022/Sites.csv')
fig4_data <- fig3_data
fig4_data_joined <- left_join(fig4_data, fig4_sites, by='SITE_NO')
# view(fig4_data_joined)
# create world map
fig4_world <- ne_countries(scale='medium', returnclass='sf')
fig4_world_map <- ggplot(fig4_world) +
  geom_sf() +
  theme_bw() +
  labs(title='World Map', x='Longitude', y='Latitude') +
  geom_point(data=fig4_data_joined, aes(DEC_LONG_VA, DEC_LAT_VA, size=RESULT_VA, color=COUNTY_NM.x), alpha=0.45) +
  labs(title='Map of California Sampling Sites',
       subtitle=paste0('A total of ', (length(fig4_data_joined$SITE_NO)), ' sites'),
       color='Californian County', size='Max Imidacloprid concentration (ug/kg)', 
       alpha=NA) +
  coord_sf(xlim=c(min(sites$DEC_LONG_VA) - 1, max(sites$DEC_LONG_VA) + 1),
           ylim=c(min(sites$DEC_LAT_VA) - 1, max(sites$DEC_LAT_VA)) + 1)
fig4_world_map
```
# Repeat thte same process; however, now use data from different region; I'll be repeating w/ data using NESQA
```{r}
fig5_data <- read.csv('G:/My Drive/ComputationalStuff/UrbanEcosystems/Git/RSQA_worksheet/1.28.2022.NESQA_ConstituentGroups=Organics,Pesticides/Results.csv')
# view(fig5_data)
fig5_data %>% 
  group_by(PARM_NM) %>% 
  summarise(counts=n()) %>% 
  arrange(desc(counts)) %>%
  head() # using 1H-1,2,4-Triazole, wf

fig5_data <- fig5_data %>% 
  filter(PARM_NM=='1H-1,2,4-Triazole, wf') %>% 
  group_by(SITE_NO) %>%
  top_n(1, RESULT_VA) %>% 
  select(SITE_NO, RESULT_VA, COUNTY_NM)
# make jitter plot
ggplot(fig5_data, aes(COUNTY_NM, RESULT_VA)) +
  geom_jitter(aes(col=COUNTY_NM)) +
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.text.x.bottom= element_blank()) +
  labs(y='Max Concentration of s-Triazole per site (ug/kg)', col='Counties')
```
##Fig6
```{r}
fig6_sites <- read.csv('G:/My Drive/ComputationalStuff/UrbanEcosystems/Git/RSQA_worksheet/1.28.2022.NESQA_ConstituentGroups=Organics,Pesticides/Sites.csv')
fig6_data <- fig5_data
fig6_data_joined <- left_join(fig6_data, fig6_sites, by='SITE_NO')
# view(fig4_data_joined)
# create world map
fig6_world <- ne_countries(scale='medium', returnclass='sf')
fig6_world_map <- ggplot(fig6_world) +
  geom_sf() +
  theme_bw() +
  labs(title='World Map', x='Longitude', y='Latitude') +
  geom_point(data=fig6_data_joined, aes(DEC_LONG_VA, DEC_LAT_VA, size=RESULT_VA, color=COUNTY_NM.x), alpha=0.45) +
  labs(title='Map of NESQA Sampling Sites',
       subtitle=paste0('A total of ', (length(fig6_data_joined$SITE_NO)), ' sites'),
       color='North East Counties', size='Max s-Triazole concentration (ug/kg)', 
       alpha=NA)+
  coord_sf(xlim=c(min(fig6_data_joined$DEC_LONG_VA) - 1, max(fig6_data_joined$DEC_LONG_VA) + 1),
           ylim=c(min(fig6_data_joined$DEC_LAT_VA) - 1, max(fig6_data_joined$DEC_LAT_VA)) + 1)
fig6_world_map
```

#Non-detects section
```{r}
# THESE TWO PARTS BELOW: are from steps 12-13; shall serve as refereshers of our data
# show the frequency of parameter measurements done based on the PARM_NM column
exp_count <- mydata %>% 
  group_by(PARM_NM) %>% 
  summarise(count=n())

# create hist
param_count_hist <- ggplot(exp_count, aes(count)) +
  geom_histogram(binwidth=50) +
  labs(title='Distribution showing the number of a unique parameter\'s
  measurements [x] and respective frequency [y]', x='Measurements on a unique
  parameter') +
  theme_classic()
param_count_hist

# now, we'll only select measurements that were detected meaning non-zero measurements
detectcount <- mydata %>% 
  filter(REMARK_CD != '<') %>% # filter out detects
  filter(RESULT_VA != 'NA') %>% # NAs; note: NA=not measured 
  filter(REMARK_CD != 'NA') %>% 
  group_by(PARM_NM) %>%
  summarise(count=n()) #%>%
  #arrange(desc(count))

detectcount #compare detectcount vs. original data set
exp_count #we obviously see noticeably more observation in exp_count than detectcount

# plot hist of detectcount
detectcount_hist <- ggplot(detectcount, aes(count)) + 
  geom_histogram(binwidth=1)
detectcount_hist

# now that we know the a good portion of our data consist of non-detects, we'll be fitlering them out
mydata_corr <- mydata %>% 
  filter(RESULT_VA != 'NA') %>% # remove NAs
  filter(REMARK_CD != 'NA') %>% 
  mutate(RESULT_CORR = ifelse(REMARK_CD=='<', 0, RESULT_VA)) # we're going to assign non-detects to value 0

# sort detectcount
detectcount <- detectcount[order(detectcount$count, decreasing=T), ]
detectcount
```
#Revisiting Plotting data on maps with non-detects data added.
```{r}
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(rgeos)

# create top_5_data; below is code i used before revisiting the non-detects section
# top_5_data <- mydata[mydata$PARM_NM %in% exp_count$PARM_NM[1:5], ]
new_top_5_data <- mydata_corr[mydata_corr$PARM_NM %in% detectcount$PARM_NM[1:5], ]

# from the Sites.csv, join neww_top_5_data to have coords needed for mapping
sites_new <- read.csv('1.21.2022.CSQA_ConstituentGroups=Organics,Pesticides/Sites.csv')
new_top_5_joined <- left_join(new_top_5_data, sites_new, by='SITE_NO')

# now, lets create the map to plot our data on
new_world <- ne_countries(scale='medium', returnclass='sf')
new_world_map <- ggplot(new_world) +
  geom_sf() +
  theme_classic() +
  labs(title='World Map', x='Longitude', y='Latitude')
new_world_map

# plot data onto world map
# change title
new_world_map <- ggplot(new_world) +
  geom_sf() +
  theme_classic() +
  labs(title='Map of CSQA Top 5 Contaminants in CSQA sampling sites (after non-detect section has been editted)',
       x='Longitude', y='Latitude')
new_world_map

# add scatter plot
new_world_map <- ggplot(new_world) +
  geom_sf() +
  theme_classic() +
  labs(title='Map of Top 5 Contaminants in CSQA sampling sites',
       x='Longitude', y='Latitude',
       subtitle=paste0('A total of ',(length(unique(sites_new$SITE_NO))), ' sites')) +
  geom_point(data=new_top_5_joined, aes(DEC_LONG_VA, DEC_LAT_VA), size=1, shape=19) +
  coord_sf(xlim=c(min(sites_new$DEC_LONG_VA) - 1, max(sites_new$DEC_LONG_VA) + 1),
           ylim=c(min(sites_new$DEC_LAT_VA) - 1, max(sites_new$DEC_LAT_VA) + 1))
world_map
```
##Fig1_redo
```{r}
# get data; filter for Pyrene, solids
redo_fig1_data <- read_csv('RSQA_Problemset_Spring2022/Results.csv')
redo_fig1_data <- redo_fig1_data %>%
  filter(RESULT_VA != 'NA') %>% 
  filter(REMARK_CD != 'NA') %>% 
  mutate(RESULT_CORR = ifelse(REMARK_CD=='<', 0, RESULT_VA))

# 
# TODO: Past me put was using top_n() and present me now doesn't know why is used it. I'm going to try to figure out why 
# why I did that, but it doesn't make sense to use top_n(). With that said, I'll comment it out from this code and compare
# it to different w/ and w/out that line of code.
# TODO: UPDATE: NVM, i want to get the max concentratrion detected per site
redo_fig1_data <- redo_fig1_data %>% 
  filter(PARM_NM=='Pyrene, solids') %>% 
  group_by(SITE_NO) %>%
  top_n(1, RESULT_CORR) %>%
  select(SITE_NO, RESULT_CORR, COUNTY_NM)

# make jitter plot
ggplot(redo_fig1_data, aes(COUNTY_NM, RESULT_CORR)) +
  geom_jitter(aes(col=COUNTY_NM)) +
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.text.x.bottom= element_blank()) +
  labs(y='Max Concentration of Pyrene per site (ug/kg)', col='Californian County')
# code that i copied and paste from previous sections
# mydata_corr <- mydata %>% 
#   filter(RESULT_VA != 'NA') %>% # remove NAs
#   filter(REMARK_CD != 'NA') %>% 
#   mutate(RESULT_CORR = ifelse(REMARK_CD=='<', 0, RESULT_VA)) # we're going to assign non-detects to value 0
```
##Fig2 Redo
```{r}
# Fig2
redo_fig2_sites <- read.csv('RSQA_Problemset_Spring2022/Sites.csv')
redo_fig2_data <- redo_fig1_data
redo_fig2_data_joined <- left_join(redo_fig2_data, redo_fig2_sites, by='SITE_NO')

# create world map
redo_fig2_world <- ne_countries(scale='medium', returnclass='sf')
redo_fig2_world_map <- ggplot(redo_fig2_world) +
  geom_sf() +
  scale_size_continuous(range=c(1,10), breaks=c(50, 100, 150, 200))+
  # theme_bw() +
  # scale_size_continuous(breaks=(50, 1000, 150, 200)) +
  # scale_size_area(breaks=c(50, 100, 150, 200)) +
  labs(title='World Map', x='Longitude', y='Latitude') +
  geom_point(data=redo_fig2_data_joined, aes(DEC_LONG_VA, DEC_LAT_VA, size=RESULT_CORR, color=COUNTY_NM.x),shape=16, alpha=0.45) +
  labs(title='Map of California Sampling Sites',
       subtitle=paste0('A total of ', (length(redo_fig2_data_joined$SITE_NO)), ' sites'),
       color='Californian County', size='Max Pyrene concentration (ug/kg)', 
       alpha=NA)+
  coord_sf(xlim=c(min(redo_fig2_sites$DEC_LONG_VA)-1, max(redo_fig2_sites$DEC_LONG_VA)+1),
           ylim=c(min(redo_fig2_sites$DEC_LAT_VA)-1, max(redo_fig2_sites$DEC_LAT_VA)+1))
redo_fig2_world_map
```

